### ISSUE TITLE
GWTP 1.4 [ERROR] An internal compiler exception occurred

### ISSUE THREAD

**Issue by confile** [ArcBees/GWTP#662]
Since upgrading from GWTP 1.4 SNAPSHOT to 1.4 final I get the following compilation errors: 

```
   [ERROR] An internal compiler exception occurred
com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
	at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:121)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:295)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:284)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
	at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:67)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:380)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:292)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:284)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
	at com.google.gwt.dev.jjs.ast.JMethodCall.visitChildren(JMethodCall.java:255)
	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:248)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:380)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:292)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:284)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
	at com.google.gwt.dev.jjs.ast.JExpressionStatement.traverse(JExpressionStatement.java:42)
	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:95)
	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:350)
	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:92)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:380)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:292)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:149)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:145)
	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:380)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:292)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:284)
	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:609)
	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:578)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:380)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:292)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:284)
	at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:1502)
	at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:863)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1311)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1043)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.precompile(JavaToJavaScriptCompiler.java:959)
	at com.google.gwt.dev.jjs.MonolithicJavaToJavaScriptCompiler.precompile(MonolithicJavaToJavaScriptCompiler.java:303)
	at com.google.gwt.dev.jjs.JavaScriptCompiler.precompile(JavaScriptCompiler.java:38)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:286)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:229)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:145)
	at com.google.gwt.dev.Compiler.run(Compiler.java:206)
	at com.google.gwt.dev.Compiler.run(Compiler.java:158)
	at com.google.gwt.dev.Compiler$1.run(Compiler.java:120)
	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
	at com.google.gwt.dev.Compiler.main(Compiler.java:127)
Caused by: java.lang.NoClassDefFoundError: com/google/inject/multibindings/Multibinder
	at com.gwtplatform.dispatch.rest.rebind.action.ActionModule.addActionGenerator(ActionModule.java:28)
	at com.gwtplatform.dispatch.rest.rebind.action.ActionModule.configure(ActionModule.java:33)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
	at com.google.inject.AbstractModule.install(AbstractModule.java:118)
	at com.gwtplatform.dispatch.rest.rebind.DispatchRestRebindModule.configure(DispatchRestRebindModule.java:58)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.gwtplatform.dispatch.rest.rebind.DispatchRestIncrementalGenerator.createInjector(DispatchRestIncrementalGenerator.java:89)
	at com.gwtplatform.dispatch.rest.rebind.DispatchRestIncrementalGenerator.generateIncrementally(DispatchRestIncrementalGenerator.java:66)
	at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:754)
	at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:160)
	at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:79)
	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:276)
	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:265)
	at com.google.gwt.dev.DistillerRebindPermutationOracle.getAllPossibleRebindAnswers(DistillerRebindPermutationOracle.java:87)
	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createStaticRebindExpression(UnifyAst.java:490)
	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createRebindExpression(UnifyAst.java:448)
	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.handleMagicMethodCall(UnifyAst.java:581)
	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.endVisit(UnifyAst.java:307)
	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:250)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:380)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:292)
	... 46 more
Caused by: java.lang.ClassNotFoundException: com.google.inject.multibindings.Multibinder
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 73 more
      [ERROR] at buddyis_00046mobile_00046MobilePhoneGapIOS__EntryMethodHolder.java(3): GWT.create(DispatchRestEntryPoint.class)
         com.google.gwt.dev.jjs.ast.JMethodCall
      [ERROR] at buddyis_00046mobile_00046MobilePhoneGapIOS__EntryMethodHolder.java(3): (EntryPoint) GWT.create(DispatchRestEntryPoint.class)
         com.google.gwt.dev.jjs.ast.JCastOperation
      [ERROR] at buddyis_00046mobile_00046MobilePhoneGapIOS__EntryMethodHolder.java(3): ((EntryPoint) GWT.create(DispatchRestEntryPoint.class)).onModuleLoad()
         com.google.gwt.dev.jjs.ast.JMethodCall
      [ERROR] at buddyis_00046mobile_00046MobilePhoneGapIOS__EntryMethodHolder.java(3): ((EntryPoint) GWT.create(DispatchRestEntryPoint.class)).onModuleLoad()
         com.google.gwt.dev.jjs.ast.JExpressionStatement
      [ERROR] at buddyis_00046mobile_00046MobilePhoneGapIOS__EntryMethodHolder.java(3): {
  ((EntryPoint) new UserAgentAsserter()).onModuleLoad();
  ((EntryPoint) new DocumentModeAsserter()).onModuleLoad();
  ((EntryPoint) GWT.create(DispatchRestEntryPoint.class)).onModuleLoad();
  ((EntryPoint) GWT.create(ApplicationController.class)).onModuleLoad();
  ((EntryPoint) GWT.create(LogConfiguration.class)).onModuleLoad();
}
         com.google.gwt.dev.jjs.ast.JBlock
      [ERROR] at buddyis_00046mobile_00046MobilePhoneGapIOS__EntryMethodHolder.java(3): {
  ((EntryPoint) new UserAgentAsserter()).onModuleLoad();
  ((EntryPoint) new DocumentModeAsserter()).onModuleLoad();
  ((EntryPoint) GWT.create(DispatchRestEntryPoint.class)).onModuleLoad();
  ((EntryPoint) GWT.create(ApplicationController.class)).onModuleLoad();
  ((EntryPoint) GWT.create(LogConfiguration.class)).onModuleLoad();
}
         com.google.gwt.dev.jjs.ast.JMethodBody
      [ERROR] at buddyis_00046mobile_00046MobilePhoneGapIOS__EntryMethodHolder.java(3): public static final void init();

         com.google.gwt.dev.jjs.ast.JMethod

```
Note that my project compiles perfect with the GWTP 1.4 SNAPSHOT.

**Comment by meriouma** [comment]
Are you using maven?

**Comment by confile** [comment]
No I don't use maven.

**Comment by meriouma** [comment]
Ok, then you need to add the guice-multibindings jar to your gwt compile classpath : http://search.maven.org/remotecontent?filepath=com/google/inject/extensions/guice-multibindings/3.0/guice-multibindings-3.0.jar

**Comment by confile** [comment]
Works perfect now. Thank you @meriouma . You might this as a note to the release notes or somewhere else.

**Comment by meriouma** [comment]
Thanks for raising the issue. We are currently working on the release notes (hence why we didn't really announce the release yet! ;)) Should be done in the next days!

**Comment by confile** [comment]
Thank you. You did a great job with GWTP! I like it!
