### ISSUE TITLE
GWT 2.5.0 upgrade using gwtp 0.7

### ISSUE THREAD

**Issue by ragnarp** [ArcBees/GWTP#116]
Hello,

Thank you for this great framework :)

We are working on upgrading to gwt 2.5.0 using gwtp 0.7  and gin 1.5.
According to the error message, see exception below, it looks like the 'GinFieldManager' in gwtp is not compatible with gwt 2.5?

Could you please confirm if this is a known issue?

Thanks and Best Regards,
Ragnar

Exception:

[INFO] Caused by: java.lang.NoSuchMethodError: com.google.gwt.uibinder.rebind.FieldWriterOfGeneratedType.<init>(Lcom/google/gwt/core/ext/typeinfo/JClassType;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/google/gwt/uibinder/rebind/MortalLogger;)V
[INFO]  at com.google.gwt.uibinder.rebind.GinFieldManager.registerFieldOfGeneratedType(GinFieldManager.java:293)
[INFO]  at com.google.gwt.uibinder.rebind.UiBinderWriter.parseDocumentElement(UiBinderWriter.java:1363)
[INFO]  at com.google.gwt.uibinder.rebind.UiBinderWriter.parseDocument(UiBinderWriter.java:1073)
[INFO]  at com.google.gwt.uibinder.rebind.GinUiBinderGenerator.generateOnce(GinUiBinderGenerator.java:195)
[INFO]  at com.google.gwt.uibinder.rebind.GinUiBinderGenerator.generate(GinUiBinderGenerator.java:146)
[INFO]  at com.google.gwt.core.ext.IncrementalGenerator.generateNonIncrementally(IncrementalGenerator.java:40)
[INFO]  at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:657)
[INFO]  at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:41)
[INFO]  at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:79)
[INFO]  at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:276)
[INFO]  at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:265)
[INFO]  at com.google.gwt.dev.DistillerRebindPermutationOracle.getAllPossibleRebindAnswers(DistillerRebindPermutationOracle.java:91)
[INFO]  at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.handleGwtCreate(UnifyAst.java:355)
[INFO]  at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.handleMagicMethodCall(UnifyAst.java:433)
[INFO]  at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.endVisit(UnifyAst.java:237)
[INFO]  at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:243)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO]  ... 32 more
