### ISSUE TITLE
Upgrade slot tool when migrating from GWTP 1.4 to 1.6

### ISSUE THREAD

**Issue by ramcrys** [ArcBees/GWTP#824]
Is it still possible to use this tool https://github.com/ArcBees/gwtp-extensions/tree/master/gwtp-type-slot-upgrader to upgrade the slots related code and remove the warnings, when migrating from 1.4 to 1.6 ? 

I have tried it on my project, but after the tool runs, I got some compilation errors. 

My old project setup is GWT 2.7 + GWTP 1.4, and I have recently updated to GWT 2.8.1 + GWTP 1.6.
